spring:
  application:
    name: config-client
server:
  port: 9010 #随机端口

eureka:
  server: # 官方不存在的配置（自定义配置）
    host: 127.0.0.1
    port: 12345
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
    # 5 秒轮训一次 ->registryFetchIntervalSeconds指定的下一个注册表获取周期生效。获取过于频繁会导致GC问题
    registryFetchIntervalSeconds: 5
  instance:
    instanceId: ${spring.application.name}:${server.port}


#  cloud:
#    zookeeper:
#      enabled: false # Zookeeper 服务发现与注册失效（默认）
#    consul:
#      discovery:
#        enabled: false # Consul 服务发现与注册失效（默认）



# 默认 profile 关闭自动特性
#eureka:
#  client:
#    enabled: true # Eureka 服务发现与注册失效（默认）





--- # Profile For Zookeeper
#spring:
#  profiles: zookeeper
#  cloud:
#    zookeeper:
#      enabled: true
#      connectString: 127.0.0.1:2181

--- # Profile For Consul
#spring:
#  profiles: consul
#  cloud:
#    consul:
#      discovery:
#        enabled: true
#        ipAddress: 127.0.0.1
#        port: 8500

# 关闭心跳log
#logging:
#  level:
#    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN