spring:
  rabbitmq:
    addresses: 192.168.0.21:5672
    username: admin
    password: SY^mqPW20ex
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true